---
- hosts: worker
  become: true

  tasks:

  - name: Pull Docker image
    docker_container:
      name: static-web
      image: yourdockerhubusername/static-web:latest
      state: started
      ports:
        - "8085:80"